import Head from 'next/head'
import { useEffect,useRef,useState } from 'react'
import BIRDS from 'vanta/dist/vanta.net.min.js'
import * as THREE from "three"

import Header from '../components/header/header'
import Profile from '../components/profile/profile'
import Skills from '../components/skill/skill'

import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useTranslation } from "next-i18next";

import { StickyNav } from 'react-js-stickynav'

export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ["common"]))
    }
  };
}


export default function Home() {
  const { t, i18n } = useTranslation();
  
  const [vantaEffect,setVantaEffect] = useState(0)
  const vantaRef = useRef(null)
  useEffect(
    () =>{
      if(!vantaEffect){
        setVantaEffect(BIRDS({el:vantaRef.current,
          THREE,
          //  color: 0x37415f,
          mouseControls: true,
          touchControls: true,
          gyroControls: false,
          minHeight: 200.0,
          minWidth: 200.0,
          scale: 1.0,
          scaleMobile: 1.0,
          color: 0xfff33f,
           backgroundColor: 0xf0620,
          // points: "10.00",
          // maxDistance: "40.00",
          // spacing: "20.00",
        }))
      }
    return () => {
      if(vantaEffect) vantaEffect.destroy()
    }
    },[vantaEffect]

  )

  const style = () => {
    return (
      <style jsx>{`
        .nav {
          transition: all 0.1s linear;
          position: fixed;
          width: 100%;
        }
        .scrollNav {
          transition: all 0.5s ease-in;
          background: rgb(20 26 50);
          width: 100%;
        }
        .styl {
          padding-top: 80px;
          margin-top: 80px
        }
        .contrainner{
          max-width: 960px;
          margin: 0 auto;
        }
        .vanta-canvas{
          z-index: -2;
        }
      `}</style>
    )
  }

  
  return (
    <div ref={vantaRef}>
      <Head>
        <title>CV Yutthaphum Seekiaw</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon2.svg" />
      </Head>

      <Header></Header>
      {/* {style()}
      <StickyNav length='40'><Header></Header></StickyNav> */}
      <Profile></Profile>
      <Skills></Skills>

    </div>
  )
}
