import Head from 'next/head'
import { useEffect,useRef,useState } from 'react'
import BIRDS from 'vanta/dist/vanta.net.min.js'
import * as THREE from "three"

import profilepic from "../img/profile.jpg"
import ReactTypingEffect from 'react-typing-effect'

import Header from '../components/header/header'
import Profile from '../components/profile/profile'
import Skills from '../components/skill/skill'

export default function Home() {
  const [vantaEffect,setVantaEffect] = useState(0)
  const vantaRef = useRef(null)
  useEffect(
    () =>{
      if(!vantaEffect){
        setVantaEffect(BIRDS({el:vantaRef.current,
          THREE,
           color: 0x37415f,
           backgroundColor: 0xf0620,
          // points: "10.00",
          // maxDistance: "40.00",
          // spacing: "20.00",
        }))
      }
    return () => {
      if(vantaEffect) vantaEffect.destroy()
    }
    },[vantaEffect]

  )
  return (
    <div ref={vantaRef}>
      <Head>
        <title>CV Yutthaphum Seekiaw</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header></Header>
      <Profile></Profile>
      <Skills></Skills>
      {/* <div className='content'>
        <h1>PPPPPPPPPPPPPPPPPPP</h1>
      </div> */}
      {/* <main className={styles.main} >
      <Image
      className={indexStyle.profilepic}
      src={profilepic}
      alt="profile"
      width={248}
      height={248}
     />
      <div><p className={indexStyle.namedev}>Mr. Yutthaphum Seekiaw</p></div>
      <div>
      <ReactTypingEffect text={["I am Programmer","I am Developer"]} speed={80} eraseDelay={200} className={indexStyle.typingeffect} />
      </div>
      </main> */}

    </div>
  )
}
